#!/bin/sh

if ! [ $(id -u) = 0 ]; then
   echo "This script must be run as root! Try 'sudo uninstall-sinatra-shell'."
   exit 1
fi

while true; do
    read -p "Uninstall sinatra-shell? " yn
    case $yn in
        [Yy]* )
          rm /usr/local/bin/sinatra-shell
          rm -rf /usr/local/bin/sinatra-shell-files
          rm /usr/local/bin/uninstall-sinatra-shell
          echo "sinatra-shell has been uninstalled."
          break;;
        [Nn]* )
          echo "sinatra-shell has NOT been uninstalled."
          exit;;
        * ) echo "Please answer yes or no.";;
    esac
done